# Welcome to Serverless!

service: ec2service
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-2

package:
  exclude:
    - node_modules/**
    - __test__/**
    - __mock__/**
    - .eslintrc.js
    - README.md
    - output_images/**

functions:
  ec2Service:
    handler: ec2Service/ec2Handler.details
    description: Get ec2 security groups for given aws account.
    events:
      - http:
          path: ec2-details
          method: get
